baseURL = "https://mrcote.ca/"
languageCode = "en-ca"
title = "mr mr cote"
theme = "papermod"
enableRobotsTXT = true

[params]
author = "Mark Cote"
Tagline = "Educational, Investigative, and Absurd Writings by M. R. Côté"
GithubUsername = "markrcote"

[taxonomies]
category = "categories"

[permalinks]
posts = "/blog/:year/:month/:day/:title"
